databases:
  - name: FriendApp
    databaseName: friendapp
    user: friendapp

services:
  - type: web
    name: FriendApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: FriendApp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false